### ISSUE TITLE
Problem with Suna Seni/Valygar installation

### ISSUE THREAD

**Issue by dranor11** [Pocket-Plane-Group/UnfinishedBusiness#18]
The Suna Seni/Valygar Relationship Restoration can't be installed with german translation. All other restorations do work. I tested the files in the suna folder - if they are exchanged with the files from version 26 there is only a parsing error from CCSUNA.baf at line 7 column 16-91 but the installation itself is successfull. Game was freshly installed, started and a savegame created.
[SETUP-UB.log](https://github.com/Pocket-Plane-Group/UnfinishedBusiness/files/5824790/SETUP-UB.log)

**Comment by AngelGryph** [comment]
Confirmed, string @349 is missing from lang/german/ubdialog.tra, but present in the english and french versions.

English version reads "Ugh, is there no place to be alone in this city?"

**Comment by AngelGryph** [comment]
Fixed locally, fix will be in the next version.
