### ISSUE TITLE
Item Restorations: assigns wrong string to blun11.itm in BGT

### ISSUE THREAD

**Issue by Gitjas** [Pocket-Plane-Group/UnfinishedBusiness#20]
From "ub/items/setup_item_restorations.tpa":
```
    // Restore proper name and description to Krotan's Skullcrusher
    COPY_EXISTING "blun11.itm" "override"
      SAY NAME2 #103012
      SAY IDENTIFIED_DESC #103013
      BUT_ONLY_IF_IT_CHANGES
```

The string 103012 doesn't exist in BGT, this gives a random mod added string to the weapon. In EET (and probably BGII:EE) this works.

**Comment by Gitjas** [comment]
Same for string number 103013.

**Comment by AngelGryph** [comment]
Verified, these strings do not exist in old BG2 and thus BGT.  Will fix in next release.

**Comment by AngelGryph** [comment]
Fixed locally, solution will be in next version.
