### ISSUE TITLE
Install error on BGII with weidu v246

### ISSUE THREAD

**Issue by Gitjas** [Pocket-Plane-Group/UnfinishedBusiness#21]
I'm getting this error if I try to install the mod on my BGII (from GOG, BG2Fixpack is installed) using weisu v246:
`ERROR Installing [The Kidnapping of Boo by Cliffette], rolling back to previous state
Unable to Unlink [weidu_external/backup/ub/0/OTHER.0]: Unix.Unix_error(1, "unlink", "weidu_external/backup/ub/0/OTHER.0")
[weidu_external/backup/ub/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   0 files for [UB/SETUP-UB.TP2] component 0.
Uninstalled      0 files for [UB/SETUP-UB.TP2] component 0.
Unable to Unlink [weidu_external/backup/ub/0/READLN.0]: Unix.Unix_error(20, "unlink", "weidu_external/backup/ub/0/READLN.0")
Unable to Unlink [weidu_external/backup/ub/0/READLN.0.TEXT]: Unix.Unix_error(20, "unlink", "weidu_external/backup/ub/0/READLN.0.TEXT")
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  0 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 1000 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  3 Installed
ERROR: Sys_error("weidu_external/lib/sfo_immutable.tph: No such file or directory")`

**Comment by Gitjas** [comment]
Sorry for the format. new try:

ERROR Installing [The Kidnapping of Boo by Cliffette], rolling back to previous state
Unable to Unlink [weidu_external/backup/ub/0/OTHER.0]: Unix.Unix_error(1, "unlink", "weidu_external/backup/ub/0/OTHER.0")
[weidu_external/backup/ub/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   0 files for [UB/SETUP-UB.TP2] component 0.
Uninstalled      0 files for [UB/SETUP-UB.TP2] component 0.
Unable to Unlink [weidu_external/backup/ub/0/READLN.0]: Unix.Unix_error(20, "unlink", "weidu_external/backup/ub/0/READLN.0")
Unable to Unlink [weidu_external/backup/ub/0/READLN.0.TEXT]: Unix.Unix_error(20, "unlink", "weidu_external/backup/ub/0/READLN.0.TEXT")
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  0 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 1000 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  3 Installed
ERROR: Sys_error("weidu_external/lib/sfo_immutable.tph: No such file or directory")

**Comment by Gitjas** [comment]
Was with v246.

**Comment by AngelGryph** [comment]
Use the version of WeiDU UB is shipped with.  That would be 247.  There is no way to make UB compatible with older versions.

**Comment by Gitjas** [comment]
Yes, it only occurred to me later that this might be the cause.

**Comment by AngelGryph** [comment]
It happens.  Mm, maybe it's better if I add a note about this in the readme.
