### ISSUE TITLE
Czech Translation of Unfinished Business v28

### ISSUE THREAD

**Issue by Rosterius** [Pocket-Plane-Group/UnfinishedBusiness#27]
I finished translating all the missing texts and did a complete revision and correction of the old texts (they really needed it).

Here is the new Czech translation.
I would appreciate it if it was officially added to the mod.

[ub-v28.CZ.zip](https://github.com/Pocket-Plane-Group/UnfinishedBusiness/files/9152648/ub-v28.CZ.zip)

Best regards

Radim **"Edvin"** Klímek

**Comment by AngelGryph** [comment]
Pushed updated Czech translation files to master.
