### ISSUE TITLE
No Installer for Version 29

### ISSUE THREAD

**Issue by Felipefpl** [Pocket-Plane-Group/UnfinishedBusiness#38]
@ALIENQuake - Why is there no installer for version 29 even though it's shown in the 1st page a version 29 exists?

**Comment by ALIENQuake** [comment]
@Felipefpl Why are you asking me?

**Comment by Felipefpl** [comment]
I assumed you are the project leader. :)

**Comment by AngelGryph** [comment]
v29 has not been released yet.
