### ISSUE TITLE
Freeze EET if installing in french

### ISSUE THREAD

**Issue by zelurker** [Pocket-Plane-Group/UnfinishedBusiness#6]
From memory it's the kind of bug where some non utf8 strings where installed.
It's with a test build of eet, not sure it happens with bg2ee native.
How to reproduce : just try to install any quest which affects dialogs in french, then try to launch the game in french -> freeze with the message "initalizing quests".
Did not happen with the previous ub version I used, I upgraded for eet.

As a workaround, I install it in english, it works.

**Comment by AngelGryph** [comment]
Unable to reproduce.  French translation was not changed between versions except for the addition of one single string by the original translator, is not treated any different from any other translation, and works normally on BG2EE.
